import bz2
import base64
from pathlib import Path

with open('template.papi', 'rb') as input_file:
    with open('papi_template.py', 'wt') as output_file:
        output_file.write(
            f'############################################################################\n'
            f'# This file is generated by {Path(__file__).name}, DO NOT EDIT !!!\n'
            f'############################################################################\n'
            f'import bz2\n'
            f'import base64\n'
            f'from pathlib import Path\n'
            f'\n'
            f'\n'
            f'def create_empty_papi_database(file: Path):\n'
            f'\twith open(file, \'wb\') as f:\n'
            f'\t\tf.write(\n'
            f'\t\t\tbz2.decompress(\n'
            f'\t\t\t\tbase64.decodebytes(\n'
            f'\t\t\t\t\t{base64.b64encode(bz2.compress(input_file.read()))}\n'
            f'\t\t\t\t)\n'
            f'\t\t\t)\n'
            f'\t\t)\n')
