"""Scheveningen team-pairing system.

A Scheveningen is a match between exactly two teams in which every player
of one team meets every player of the other. On *n* boards that takes *n*
rounds; played twice (double round) it takes 2*n*, the second half
repeating the first in reverse order with the colours swapped, which is
what keeps anyone from having three of the same colour in a row.

The tables are the ones Otto Milvang recommends in "Scheveningen system"
(29 September 2022): those generated by Bousios Hristos's method, rather
than the older ad-hoc tables of the FIDE Arbiters' Manual. Milvang's
requirements, in priority order, are

1. every player of one team plays every player of the other;
2. no two players meet more than once;
3. the white/black difference is minimised — over the teams, over each
   player's whole match, over a player's consecutive games, and within
   a round.

Sizes where *n* divided by 4 leaves 2 (6, 10, 14…) admit no perfect
solution; 6 and 10 use the published hand-made tables below, and the
larger ones fall back to the generated compromise.

The board order is stable: board *j* always seats the *j*-th player of
team A, and team B rotates around it.
"""

from abc import ABC
from functools import cached_property, lru_cache
from typing import TYPE_CHECKING, override

from common.i18n import _
from data.pairings.engines import PairingEngine, TeamPairingEngine
from data.pairings.fixed_table import (
    FixedPairingTable,
    PairingTableProvider,
    TablePairing,
)
from data.pairings.settings import PairingSetting
from data.pairings.systems import PairingSystem, swiss_style_permission_handler
from data.pairings.variations import PairingVariation
from data.safety_mode import PairingAction, PermissionHandler
from database.sqlite.event.event_store import StoredBoard, StoredTeamBoard
from utils.entity import EntityManager, EventBoundEntityManager

if TYPE_CHECKING:
    from data.event import Event
    from data.player import Player
    from data.teams.team import Team
    from data.teams.team_board import TeamBoard
    from data.tournament import Tournament


# The two sizes with no generated solution, transcribed from Milvang's
# paper. The magnitude is the 1-based B-player, the sign its colour:
# positive means the B-player has white.
#
# 5 is deliberately *not* tabulated, though the paper prints a table for
# it that the rule below does not reproduce (board 3 of round 2 is
# A3-B4 here, B4-A3 there). The two are the same schedule with the same
# ten colour sequences, merely dealt to opposite sides of the match, and
# they tie on every requirement the paper states — so the generated one
# is used, which keeps every odd size under a single rule. Wikipedia,
# which carries the same table set, agrees with the generated one.
_SB6: tuple[tuple[int, ...], ...] = (
    (-1, 2, 3, -4, 5, -6),
    (2, -3, -5, 6, -4, 1),
    (-3, 5, 1, -2, -6, 4),
    (4, 6, -2, -1, 3, -5),
    (-5, -4, -6, 3, 1, 2),
    (6, -1, 4, 5, -2, -3),
)

_SB10: tuple[tuple[int, ...], ...] = (
    (-1, -2, -3, -4, 5, 6, 7, -8, 9, 10),
    (2, 1, 8, 3, -10, -5, -6, 4, -7, -9),
    (-3, -8, -4, -10, 6, 7, 9, -1, 2, 5),
    (4, 3, 10, -6, -7, 8, -5, -9, 1, -2),
    (-5, -4, 9, 7, 1, -10, 8, 2, -3, -6),
    (6, -7, -1, -9, -8, -2, 10, 5, 4, 3),
    (-7, 5, 2, 1, 4, 9, -3, -10, -6, -8),
    (8, 6, -5, -2, -9, -1, -4, 3, 10, 7),
    (-9, -10, -7, 5, 2, 3, 1, -6, -8, 4),
    (10, 9, 6, 8, -3, -4, -2, 7, -5, -1),
)


_TABULATED: dict[int, tuple[tuple[int, ...], ...]] = {6: _SB6, 10: _SB10}


def scheveningen_grid(players: int) -> tuple[tuple[tuple[int, bool], ...], ...]:
    """The raw schedule for *players* boards, indexed ``[round][board]``.

    Each cell is ``(b_index, b_is_white)``: the 0-based player of team B
    facing the board's team-A player, and which side has white. Board
    *j* always seats team A's *j*-th player, so only B moves.
    """
    if players < 2:
        raise ValueError(f'A Scheveningen needs at least 2 boards, got {players}.')
    half = players // 2
    # opponent[round][board] and b_is_white[round][board].
    opponent = [[0] * players for __ in range(players)]
    b_is_white = [[False] * players for __ in range(players)]

    if players in _TABULATED:
        table = _TABULATED[players]
        return tuple(
            tuple((abs(cell) - 1, cell > 0) for cell in table[round_])
            for round_ in range(players)
        )

    if players % 2:
        # Odd: a plain rotation, with the colours of each round derived
        # from the previous one so that they alternate per player.
        for round_ in range(players):
            for board in range(players):
                opponent[round_][board] = (round_ + board) % players
        for board in range(players):
            b_is_white[0][board] = board > half
        for round_ in range(1, players):
            for board in range(players):
                b_is_white[round_][board] = not b_is_white[round_ - 1][
                    (board + (round_ & 1)) % players
                ]
    else:
        # Two interleaved rotations of half the size: the top-left and
        # bottom-right quadrants rotate among the first half of each
        # team, the other two quadrants across the halves.
        for round_ in range(half):
            for board in range(half):
                rotated = (round_ + board) % half
                opponent[round_][board] = rotated
                opponent[round_][board + half] = rotated + half
                opponent[round_ + half][board] = rotated + half
                opponent[round_ + half][board + half] = rotated
        if players % 4 == 2:
            # No perfect colour scheme exists at these sizes: the two
            # middle rounds give the whole team one colour, the rest
            # split. (6 and 10 are tabulated above.)
            for round_ in range(players):
                for board in range(players):
                    if round_ in (half - 1, half) or board < half:
                        b_is_white[round_][board] = bool(round_ & 1)
                    else:
                        b_is_white[round_][board] = not (round_ & 1)
        else:
            # n divisible by 4: each round splits the boards evenly.
            for round_ in range(players):
                for board in range(players):
                    if board < half:
                        b_is_white[round_][board] = bool(round_ & 1)
                    else:
                        b_is_white[round_][board] = not (round_ & 1)

    return tuple(
        tuple(
            (opponent[round_][board], b_is_white[round_][board])
            for board in range(players)
        )
        for round_ in range(players)
    )


def _cell_to_pairing(board: int, b_index: int, b_is_white: bool) -> TablePairing:
    if b_is_white:
        return TablePairing(
            white_team='B',
            white_index=b_index + 1,
            black_team='A',
            black_index=board + 1,
        )
    return TablePairing(
        white_team='A',
        white_index=board + 1,
        black_team='B',
        black_index=b_index + 1,
    )


def _reversed_colours(pairing: TablePairing) -> TablePairing:
    return TablePairing(
        white_team=pairing.black_team,
        white_index=pairing.black_index,
        black_team=pairing.white_team,
        black_index=pairing.white_index,
    )


@lru_cache(maxsize=None)
def scheveningen_table(players_per_team: int, double_round: bool) -> FixedPairingTable:
    """The Scheveningen table for a match on *players_per_team* boards."""
    rounds: list[tuple[TablePairing, ...]] = [
        tuple(
            _cell_to_pairing(board, b_index, b_is_white)
            for board, (b_index, b_is_white) in enumerate(cells)
        )
        for cells in scheveningen_grid(players_per_team)
    ]
    if double_round:
        # The return match is played back to front with the colours
        # swapped, which is what avoids three same-coloured games in a
        # row at the turn.
        rounds += [
            tuple(_reversed_colours(pairing) for pairing in round_)
            for round_ in reversed(rounds)
        ]
    return FixedPairingTable(
        team_count=2,
        players_per_team=players_per_team,
        rounds=tuple(rounds),
        # 6, 10, 14… boards have no perfect solution; the tables used
        # there deliberately relax the colour balance.
        is_compromise=players_per_team % 4 == 2 and players_per_team > 2,
    )


class ScheveningenPairingSystem(
    PairingSystem['ScheveningenVariation'], PairingTableProvider
):
    """A match between two teams, board by board, over as many rounds as
    there are boards.

    Every round opposes the same two teams, so every round is a match and
    is scored as one. What the table settles is who meets whom on which
    board, and with which colour — which is why the colour pattern and
    the colour-preference rules have nothing to say here.
    """

    MIN_BOARDS = 2
    TEAM_COUNT = 2

    @staticmethod
    def static_id() -> str:
        return 'SCHEVENINGEN'

    @staticmethod
    def static_name() -> str:
        return _('Scheveningen')

    @override
    def variation_manager(
        self, event: 'Event'
    ) -> EntityManager['ScheveningenVariation']:
        return ScheveningenVariationManager(event)

    @property
    def pairing_buttons_template(self) -> str:
        # Round by round, so each team can edit its lineup between them.
        return '/admin/pairings/swiss_pairing_buttons.html'

    @property
    @override
    def uses_colour_pattern(self) -> bool:
        # The table names the colour of every board itself.
        return False

    @property
    @override
    def uses_team_letters(self) -> bool:
        # The table addresses the two teams as A and B.
        return True

    @property
    @override
    def supports_complementary_pairings(self) -> bool:
        return False

    @property
    @override
    def predetermined_pairings(self) -> bool:
        # Who meets whom on which board is settled before the first move.
        return True

    @property
    @override
    def allow_rounds_update_once_started(self) -> bool:
        # The round count is the size of the match; changing it midway
        # would re-cut the table.
        return False

    @property
    @override
    def allow_player_addition_once_paired(self) -> bool:
        return False

    @property
    @override
    def allow_team_addition_once_paired(self) -> bool:
        # A third team has no place in a match.
        return False

    @property
    @override
    def allow_bye_definition(self) -> bool:
        return False

    @property
    @override
    def show_unpaired_player_modal(self) -> bool:
        return False

    @property
    @override
    def show_unpaired_team_modal(self) -> bool:
        # Both teams are paired by the table, every round.
        return False

    @property
    @override
    def split_unpaired_and_bye_players(self) -> bool:
        return False

    @cached_property
    def permission_handler(self) -> PermissionHandler[PairingAction]:
        return swiss_style_permission_handler(protect_unpairing=False)

    def default_current_round(self, tournament: 'Tournament') -> int:
        return tournament.last_paired_round

    @override
    def get_table(
        self,
        team_count: int,
        players_per_team: int,
        tournament: 'Tournament | None' = None,
    ) -> FixedPairingTable | None:
        if team_count != self.TEAM_COUNT or players_per_team < self.MIN_BOARDS:
            return None
        double_round = False
        if tournament is not None:
            variation = tournament.pairing_variation
            double_round = (
                isinstance(variation, ScheveningenVariation) and variation.double_round
            )
        return scheveningen_table(players_per_team, double_round)


class ScheveningenEngine(TeamPairingEngine):
    """Pairs the round as the match it is: one team_board envelope over
    every board of the round, which is what earns each round its match
    points. The seating comes from the table rather than from the two
    lineups read straight across — board *j* keeps team A's *j*-th
    player, and team B moves around it from round to round."""

    @property
    def system(self) -> ScheveningenPairingSystem:
        return ScheveningenPairingSystem()

    def round_pairings(
        self, tournament: 'Tournament', round_: int
    ) -> tuple[TablePairing, ...]:
        """The table's cells for *round_*, in board order. Empty when
        the tournament's shape has no table or the round is past its
        end — the pairing buttons carry the reason."""
        table = self.system.get_table(
            len(self._teams_for_tournament(tournament)),
            tournament.team_player_count or 0,
            tournament,
        )
        if table is None:
            return ()
        try:
            return table.round_pairings(round_, tournament.rounds)
        except ValueError:
            return ()

    @override
    def invalid_player_count_message(self, tournament: 'Tournament') -> str | None:
        teams = self._teams_for_tournament(tournament)
        if len(teams) != self.system.TEAM_COUNT:
            return _('A Scheveningen is a match between exactly two teams.')
        boards = tournament.team_player_count or 0
        if boards < self.system.MIN_BOARDS:
            return _('A Scheveningen is played on {min} boards at least.').format(
                min=self.system.MIN_BOARDS
            )
        expected = tournament.pairing_variation.automatic_round_count(tournament)
        if expected is not None and tournament.rounds != expected:
            return _(
                'A Scheveningen on {boards} boards is played over {expected} '
                'rounds, so that every player meets every opponent.'
            ).format(boards=boards, expected=expected)
        return None

    @override
    def pairings_generation_disabled_message(
        self, tournament: 'Tournament', at_round: int
    ) -> str | None:
        if message := super().pairings_generation_disabled_message(
            tournament, at_round
        ):
            return message
        teams = self._teams_for_tournament(tournament)
        if not any(
            player is not None
            for team in teams
            for player in team.effective_round_slots(at_round)
        ):
            return _('Pairings generation disabled if there are no players to pair.')
        if any(
            not tournament.is_round_finished(round_) for round_ in range(1, at_round)
        ):
            return _(
                'Pairings generation not allowed if previous rounds have '
                'missing results.'
            )
        return None

    @override
    def generate_pairings(
        self,
        tournament: 'Tournament',
        round_: int,
        partial_pairings: bool = False,
    ) -> str:
        if self.pairings_generation_disabled_message(tournament, round_):
            raise ValueError(
                f'Pairings generation not allowed for round {round_} '
                f'of tournament [{tournament.name}].'
            )
        teams = self._teams_for_tournament(tournament)
        if not self.round_pairings(tournament, round_):
            return _('Pairing is not possible.')
        team_a, team_b = teams
        self._persist_team_round(tournament, round_, [(team_a.id, team_b.id)])
        return ''

    @override
    def _team_match_stored_boards(
        self,
        tournament: 'Tournament',
        stb: StoredTeamBoard,
    ) -> list[StoredBoard]:
        """Seat the round's boards from the table. Letter ``A`` is the
        envelope's team_a — the engine always pairs the two teams in
        their canonical order — and the cell's own sides give the
        colours, so no colour pattern is consulted."""
        team_a = tournament.event.teams_by_id[stb.team_a_id]
        team_b = (
            tournament.event.teams_by_id[stb.team_b_id]
            if stb.team_b_id is not None
            else None
        )
        n = tournament.team_player_count or 0
        slots_by_letter: dict[str, list['Player | None']] = {
            'A': list(team_a.effective_round_slots(stb.round_)),
            'B': list(team_b.effective_round_slots(stb.round_))
            if team_b is not None
            else [None] * n,
        }

        def player_id(letter: str, index_1based: int) -> int | None:
            # Hole-aware: ``effective_round_slots`` carries a ``None``
            # at each seat the team left empty.
            slots = slots_by_letter.get(letter, [])
            index = index_1based - 1
            player = slots[index] if 0 <= index < len(slots) else None
            return player.id if player is not None else None

        return [
            StoredBoard(
                id=None,
                white_player_id=player_id(pairing.white_team, pairing.white_index),
                black_player_id=player_id(pairing.black_team, pairing.black_index),
                index=board_index,
                team_board_id=stb.id,
            )
            for board_index, pairing in enumerate(
                self.round_pairings(tournament, stb.round_)
            )
        ]

    @override
    def team_seat_owner(
        self,
        tournament: 'Tournament',
        team_board: 'TeamBoard',
        board_index: int,
        physical_side: str,
    ) -> 'Team | None':
        if team_board.team_b is None:
            return None
        pairings = self.round_pairings(tournament, team_board.round)
        if not 0 <= board_index < len(pairings):
            return None
        pairing = pairings[board_index]
        letter = pairing.white_team if physical_side == 'white' else pairing.black_team
        return team_board.team_a if letter == 'A' else team_board.team_b

    @override
    def team_board_slots(
        self,
        tournament: 'Tournament',
        team_board: 'TeamBoard',
        team_id: int,
    ) -> dict[int, int]:
        letter = 'A' if team_id == team_board.stored_team_board.team_a_id else 'B'
        slots: dict[int, int] = {}
        for board_index, pairing in enumerate(
            self.round_pairings(tournament, team_board.round)
        ):
            if pairing.white_team == letter:
                slots[board_index] = pairing.white_index - 1
            elif pairing.black_team == letter:
                slots[board_index] = pairing.black_index - 1
        return slots


class ScheveningenVariation(PairingVariation, ABC):
    @staticmethod
    def system() -> 'ScheveningenPairingSystem':
        return ScheveningenPairingSystem()

    @property
    def double_round(self) -> bool:
        """Whether the match is played twice, colours reversed."""
        return False

    @property
    @override
    def sets_its_own_round_count(self) -> bool:
        return True

    @override
    def automatic_round_count(self, tournament: 'Tournament') -> int | None:
        boards = tournament.team_player_count or 0
        if boards < ScheveningenPairingSystem.MIN_BOARDS:
            return None
        return boards * (2 if self.double_round else 1)

    @property
    def engine(self) -> PairingEngine:
        return ScheveningenEngine()

    @property
    def settings(self) -> list[PairingSetting]:
        return []

    @property
    def trf_encoded_type(self) -> str:
        # No FIDE TRF26 team code covers the Scheveningen.
        return 'CUSTOM_SCHEVENINGEN'


class StandardScheveningenVariation(ScheveningenVariation):
    @staticmethod
    def variation_id() -> str:
        return 'STANDARD'

    @staticmethod
    def static_name() -> str:
        return _('Scheveningen')


class DoubleScheveningenVariation(ScheveningenVariation):
    @staticmethod
    def variation_id() -> str:
        return 'DOUBLE'

    @staticmethod
    def static_name() -> str:
        return _('Double-round Scheveningen')

    @property
    @override
    def double_round(self) -> bool:
        return True


class ScheveningenVariationManager(EventBoundEntityManager[ScheveningenVariation]):
    @override
    def entity_types(self) -> list[type[ScheveningenVariation]]:
        return [StandardScheveningenVariation, DoubleScheveningenVariation]
